# Generated by Django 2.1.7 on 2019-04-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_BOJid', models.CharField(max_length=100)),
                ('problem_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HongikNotSolvedProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HongikSolvedProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOJid', models.CharField(max_length=100, unique=True)),
                ('accept_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('solved_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='hongiksolvedproblem',
            name='problem_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalPage.Problem'),
        ),
        migrations.AddField(
            model_name='hongiknotsolvedproblem',
            name='problem_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalPage.Problem'),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='member_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalPage.Member'),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='problem_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalPage.Problem'),
        ),
    ]
