# Generated by Django 2.1.7 on 2019-03-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solvedNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOJid', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='acceptance',
            name='solved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalPage.Problem'),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalPage.Member'),
        ),
    ]
